<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @author Nils - Deele (nils@dfworks.lv)
 * @version $Id: $
 */
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Pievieno izsekoðanas ID, profila ID un pieejas virkni galvenajam konfigurâcijas failam.',
	'Administration' => 'Goldwood administrâcija',
	'Are you sure you want to delete this item?' => 'Vai patieðâm vçlies dzçst ðo ierakstu?',
	'Avg. Time on Page' => 'Vidçjais pavadîtais laiks lapâ',
	'Avg. Visit Duration' => 'Vidçjais apmeklçjuma ilgums',
	'Bounce Rate' => 'Pârlekðanas bieþums',
	'CSV' => 'CSV',
	'Changes saved.' => 'Izmaiòas saglabâtas.',
	'Changes saved. You can add a new entry.' => 'Izmaiòas saglabâtas. Vari pievienot jaunu ierakstu.',
	'Choose {name}' => 'Izvçlies {name}',
	'Connect' => 'Pieslçgt',
	'Connect with your Google Analytics account.' => 'Pieslçdz savu Google Analytics kontu.',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Neizdevâs izveidot mapi "{dir}". Pârliecinies, ka "uploads" mapç ir atïauts veikt izmaiòas.',
	'Could not create upload folder "{dir}".' => 'Neizdevâs izveidot augðuplâdes mapi "{dir}".',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'Neizdevâs dzçst ierakstu "{name}" ar ID "{pk}".',
	'Could not load model "{name}".' => 'Neizdevâs ielâdçt "{name}" modeli.',
	'Could not save file or file exists: "{file}".' => 'Neizdevâs saglabât datni "{file}", vai arî datne ar ðâdu nosaukumu jau eksistç.',
	'Could not upload file.' => 'Neizdevâs augðuplâdet datni.',
	'Create' => 'Izveidot',
	'Create {name}' => 'Izveidot {name}',
	'Delete' => 'Dzçst',
	'Desktop Pageviews' => 'Darbvirsmas skatîjumi',
	'Device Traffic' => 'Ierîces joslas noslodze',
	'Direct {percentage}' => 'Tieðâ {percentage}',
	'Download' => 'Lejuplâdçt',
	'Download {name}' => 'Lejuplâdçt {name}',
	'Edit {name}' => 'Rediìçt {name}',
	'Error' => 'Kïûda',
	'Excel' => 'Excel',
	'Google Analytics setup' => 'Google Analytics uzstâdîðana',
	'Google Analytics summary for the past {days} days' => 'Google Analytics kopsavilkums par pçdçjâ {days} dienâm',
	'Home' => 'Sâkums',
	'Image' => 'Attçls',
	'Image preview' => 'Attçla priekðskats',
	'Incorrect username or password.' => 'Nekorekts lietotâjvârds vai parole.',
	'Invalid file extension "{ext}".' => 'Nekorekts faila paplaðinâjums "{ext}".',
	'Keyword' => 'Atslçgvârds',
	'List' => 'Skatît sarakstu',
	'Login' => 'Ieiet sistçmâ',
	'Logout' => 'Atslçgties',
	'MS CSV' => 'MS CSV',
	'Metric' => 'Metriskâ',
	'New Visitors' => 'Jauni apmeklçtâji',
	'New Visits' => 'Jauni apmeklçjumi',
	'Next' => 'Tâlâk',
	'Overview' => 'Kopsavilkums',
	'Page' => 'Lappuse',
	'Pages / Visit' => 'Lapas / apmeklçjumi',
	'Pageviews' => 'Lapas skatîjumi',
	'Password' => 'Parole',
	'Paste authorization code here:' => 'Ðeit ielîmç autorizâcijas kodu:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Uzstâdi "username" un "password" moduïa îpaðîbas konfigurâcijas failâ',
	'Please enter your username and password.' => 'Ievadi savu lietotâjvârdu un paroli.',
	'Preview' => 'Priekðskats',
	'Referral {percentage}' => 'Nosûtâmais {percentage}',
	'Referrer' => 'Nostûtîtâjs',
	'Reload page' => 'Pârlâdçt lapu',
	'Remember me next time' => 'Atcerçties mani',
	'Save' => 'Saglabât',
	'Save and add another' => 'Saglabât un pievienot jaunu',
	'Save and continue editing' => 'Saglabât un turpinât rediìçðanu',
	'Search {percentage}' => 'Meklçðana {percentage}',
	'Select profile.' => 'Izvçlies profilu.',
	'Separate words with commas.' => 'Atdaliet vârdus ar komatiem.',
	'Smartphone Pageviews' => 'Viedtelefonu skatîjumi',
	'Statistics' => 'Statistika',
	'Step {num}' => 'Solis {num}',
	'Tablet Pageviews' => 'Planðetdatoru skatîjumi',
	'There was an Google Analytics API service error {code}: {message}' => 'Notika Google Analytics API kïûda {code}: {message}',
	'Top Keywords' => 'Atslçgvârdu tops',
	'Top Pages' => 'Lapu tops',
	'Top Referrers' => 'Nosûtîtâju tops',
	'Traffic Sources' => 'Joslas slodzes avoti',
	'Unable to authenticate with Auth code {code}: {message}' => 'Neizdevâs autentificçties ar autorizâcijas kodu {code}: {message}',
	'Unique Pageviews' => 'Unikâlie lapas skatîjumi',
	'Unique Visitors' => 'Unikâlie apmeklçtâji',
	'Username' => 'Lietotâjvârds',
	'Value' => 'Vçrtîba',
	'Visits' => 'Apmeklçjumi',
);